print("enter as string")
name = input()
print("enter age")
age = input()
print("enter address")
addr = input()
print("name = {}".format(name))
print("or")
print("name = {}\n age = {}\n addr = {}".format(name,age,addr))