str = "RajaRamMohanRoy"
print(len(str))
print(str)
print(str[0])
print(str[7])
print(str[-1])
print(str[-1])
print(str[-8])
print(str[-15])
print(str[0:4])
print(str[4:7])
print(str[12: ])
print(str[12: ])
print(str[:])
print(str[ :: -1])
print(str[3:9])
print(str[::3])
print(str[12:4])
print(str[5::-1])
print(str[-12:-5])#no o/p
print(str[-5:-14:-1])
print(str[ :-5:-1])
print(str[-5:-14])
print(str[7:13:0])
