print(True >= 1)
print((2**False)<=(2**True))
print("a" != 65)
#print("a">66)
print(0 and True)
print(2 or 0 or -1)
print((False and True or True)) or (10<5)
print((False or True and False) or (10>5))
print(not((10+3) and (10<15)and (8)))
print(not(not((True and False) or (1 and 2) or (False))))